name: CI
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  base:
    runs-on: ubuntu-latest
    container:
      image: "python:3.8.3"
    name: "Base pipeline"
    steps:
      - uses: actions/checkout@v2
      - name: "Pre-commit checks"
        run: |
          pip install pre-commit
          pre-commit run --all-files --show-diff-on-failure --color=always
          build:
            runs-on: ubuntu-18.04
      - name: shellcheck
        uses: ludeeus/action-shellcheck@0.1.0
  bumpAndTag:
    runs-on: ubuntu-latest
    name: "Bump and Tag"
    needs: [base]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: "Bump version and push tag"
        uses: anothrNick/github-tag-action@1b82315fa74a0572aa0bc1a96b859c57fc26e531
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
